languageCode = "en-us"
title = "Containerum Docs"
# pygmentsStyle = "monokai"
pygmentsUseClassic = true
pygmentsStyle = "monokai"

[params]
  github = "https://github.com/containerum/containerum-docs"
  issue = "Issue with"


[[menu.docs]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"

[[menu.docs]]
  name = "Installation"
  weight = 2
  identifier = "installation"
  url = "/installation/"

[[menu.docs]]
  name = "Configuration"
  weight = 3
  identifier = "configuration"
  url = "/configuration/"

[[menu.docs]]
  name = "Objects"
  weight = 4
  identifier = "objects"
  url = "/objects/"

[[menu.docs]]
  name = "CLI"
  weight = 5
  identifier = "cli"
  url = "/cli/"

[[menu.docs]]
  name = "CI/CD"
  weight = 6
  identifier = "ci-cd"
  url = "/ci-cd/"

[[menu.docs]]
  name = "FAQ"
  weight = 7
  identifier = "faq"
  url = "/faq/"

#[[menu.docs]]
#  name = "Developer Guide - API"
#  weight = 8
#  identifier = "developer-guide"
#  url = "/developer-guide/"

[[menu.docs]]
  name = "Release Notes"
  weight = 8
  identifier = "release-notes"
  url = "/release-notes/"

[[menu.docs]]
  name = "Contribute"
  weight = 9
  identifier = "contribute"
  url = "/contribute/"

[[menu.docs]]
  name = "Commands"
  weight = 10
  identifier = "commands"
  parent = "cli"
  url = "/cli/commands"
